Yeet CASC (WIP)
fedddddd/h2-mod pull request #254
Opened 2022-04-15 17:00 UTC by netadr

This is a work-in-progress effort to provide the ability to change the active implementation of `DB_FileSysInterface` to `DiskFS` instead of `BnetTACTVFSManager` (default). Using `DiskFS` as the active implementation allows for game files to be loaded directly from the filesystem, bypassing battle.net's CASC containers entirely.

2022-05-02 23:15 UTC, fedddddd commented on src/client/component/database.cpp
> +			int default_value = (utils::io::directory_exists("Data/data") && utils::io::directory_exists("Data/config") && utils::io::directory_exists("Data/indices")) ? 0 : 1;
const auto default_value = static_cast<int>(...

2022-05-02 23:18 UTC, fedddddd requested changes

2022-05-02 23:18 UTC, fedddddd commented on src/client/component/database.cpp
> +			int default_value = (utils::io::directory_exists("Data/data") && utils::io::directory_exists("Data/config") && utils::io::directory_exists("Data/indices")) ? 0 : 1;
const auto default_value = static_cast<int>(...

2022-05-02 23:18 UTC, fedddddd commented on src/client/component/database.cpp
> +			static const char* values[] = {
newline

2022-05-02 23:18 UTC, fedddddd commented on src/client/component/database.cpp
> +		utils::hook::detour db_fsinitialize_hook;
db_fs_initialize_...

2022-05-02 23:18 UTC, fedddddd commented on src/client/component/database.cpp
> +			int default_value = (utils::io::directory_exists("Data/data") && utils::io::directory_exists("Data/config") && utils::io::directory_exists("Data/indices")) ? 0 : 1;
also put a newline in between one of the &&

2022-05-02 23:58 UTC, merged

2022-05-04 00:13 UTC, diamante0018 commented on src/client/component/database.cpp
> +			const auto default_value = static_cast<int>(!utils::io::directory_exists("Data/data")
This static cast is not necessary. Bool will be promoted to an int when call register enum.
https://docs.microsoft.com/en-us/cpp/cpp/type-conversions-and-type-safety-modern-cpp?view=msvc-170#widening-conversions-promotion
Just noticed this now 😅